### ISSUE TITLE
V1.0.0 todo list

### ISSUE THREAD

**Issue by sveetch** [sveetch/py-css-styleguide#21]
- [x] Implement dart-sass behaviors support along maintained libsass compatibility, issue #19;
- [x] Ensure DeprecationWarning are show during compilation out of pytest (which enable all warning types) else move to a UserWarning instead;
- [x] Upgrade package to modern structure and config. It may be simpler to restart from last cookiecutter for Python project and replace contents with this package code and doc. In resume:
- [x] Clean useless `# -*- coding: utf-8 -*-`;
- [x] package setup should use option to require for Python version(s) so projects in unsupported Python version and that does not pin package version won't upgrade automatically to this major version;
- [x] Flake8 new config;
- [x] Use autopep8 or Black on code once (at least turn all single quote to
    double quotes where it is possible);
- [x] Python 3.8 to 3.10 or 11 support only;
- [x] Add contribution templates for issues;
- [x] Better tests structure;
- [x] Use pathlib.Path instead of os or io;
- [x] Improve documentation
  - [x] Logo ?
  - [x] Better and simpler explanations;
  - [x] Some more little usage sample;
  - [x] Better document structure;
- [x] Upgrade stylesheet version;
- [x] #22
- [x] Add documentation about "Migrate to 1.0.0";
- [x] Upgrade install and development doc;
- [x] Check django version support with sandbox from setup extra requirement "dev";

**Comment by sveetch** [comment]
Work is on the way in [branch v1.0.0](https://github.com/sveetch/py-css-styleguide/tree/v1.0.0)

**Comment by sveetch** [comment]
v1.0.0 has been released.
